09/12/2024 06:07:30 PM logger_grbl___grbl INFO <<<<<<<<<<<<<<<<<< Logger setup anew <<<<<<<<<<<<<<<<<<< (utils.py:39) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Analyzing repos/repos_400_c_round_two/grbl___grbl (install_repos.py:285) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running make (install_repos.py:51) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running command: make clean (install_repos.py:20) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Logging output to: logs/repos/repos_400_c_round_two_install_logs_with_make_cmake_gradlew_meson_scons_bazel_2024-09-12_17-35-05/grbl___grbl_build.log (install_repos.py:21) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl DEBUG rm -f grbl.hex build/*.o build/*.d build/*.elf (install_repos.py:38) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running command: make distclean (install_repos.py:20) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Logging output to: logs/repos/repos_400_c_round_two_install_logs_with_make_cmake_gradlew_meson_scons_bazel_2024-09-12_17-35-05/grbl___grbl_build.log (install_repos.py:21) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl DEBUG make: *** No rule to make target 'distclean'.  Stop. (install_repos.py:38) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running command: rm -rf autom4te.cache (install_repos.py:20) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Logging output to: logs/repos/repos_400_c_round_two_install_logs_with_make_cmake_gradlew_meson_scons_bazel_2024-09-12_17-35-05/grbl___grbl_build.log (install_repos.py:21) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running command: rm -f config.status config.cache config.log (install_repos.py:20) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Logging output to: logs/repos/repos_400_c_round_two_install_logs_with_make_cmake_gradlew_meson_scons_bazel_2024-09-12_17-35-05/grbl___grbl_build.log (install_repos.py:21) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running autogen (install_repos.py:57) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running command: ./autogen (install_repos.py:20) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Logging output to: logs/repos/repos_400_c_round_two_install_logs_with_make_cmake_gradlew_meson_scons_bazel_2024-09-12_17-35-05/grbl___grbl_build.log (install_repos.py:21) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl DEBUG /bin/sh: 1: ./autogen: not found (install_repos.py:38) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running ./configure (install_repos.py:61) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running command: ./configure (install_repos.py:20) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Logging output to: logs/repos/repos_400_c_round_two_install_logs_with_make_cmake_gradlew_meson_scons_bazel_2024-09-12_17-35-05/grbl___grbl_build.log (install_repos.py:21) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl DEBUG /bin/sh: 1: ./configure: not found (install_repos.py:38) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running make (install_repos.py:69) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Running command: make (install_repos.py:20) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl INFO Logging output to: logs/repos/repos_400_c_round_two_install_logs_with_make_cmake_gradlew_meson_scons_bazel_2024-09-12_17-35-05/grbl___grbl_build.log (install_repos.py:21) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl DEBUG avr-gcc -Wall -Os -DF_CPU=16000000 -mmcu=atmega328p -I. -ffunction-sections -fdata-sections -MMD -MP -c grbl/main.c -o build/main.o (install_repos.py:38) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl DEBUG make: avr-gcc: No such file or directory (install_repos.py:38) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl DEBUG make: *** [Makefile:53: build/main.o] Error 127 (install_repos.py:38) (grbl___grbl)
09/12/2024 06:07:30 PM logger_grbl___grbl ERROR Error: Build failed for grbl___grbl
Build failed for reason: make failed (install_repos.py:295) (grbl___grbl)
